version: '3'

networks:
  default:
    name: cumulus-api_default

services:
  pgclient:
    build:
      context: .
    environment:
      - AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
      - AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_S3_BUCKET=castle-data-develop
      - AWS_S3_ENDPOINT=http://minio:9000
      - AWS_S3_DISABLE_SSL=True
      - PGDATABASE=postgres
      - PGHOST=cumulusdb
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - SCHEMA=cumulus
      - S3_DB_EXPORT_DIR=cumulus/db_migration
      # EXPORT_TABLES=table1 table2
      # leave empty for all tables
      - EXPORT_TABLES=acquirablefile download download_product productfile
      - MODE=export

    # command: ["tail", "-f", "/dev/null"]
    # command: /bin/bash -c /app/app.sh

    # volumes:
    #   - ./app:/app
